training: !!bool "true"
device: "cuda:0"
---
data:
  sr: 25000
  frames: 24
  hop_size: 512
  n_fft: 2048
---
model:
  res_map_n: 32 # residual hidden map features
  residual_layers: 15 # Residual nets layers
  dilation_cycle: 3
  proj: 256 # Embedding size
  class_n: 2
---
train:
  train_path: '/home/vigor/DATA/SE_dis/flist/train/'
  epochs: 100000
  wav_n: 16
  batch_size: 1
  num_workers: 8
  lr: 0.001 # Learning rate
  ckpt_interval: 5
  ckpt_dir: './ckpt'
  restoring: !!bool 'False'
  restore_path: './ckpt/ckpt_'
---
test:
  test_path: '/home/vigor/DATA/SE_dis/flist/test/'